# Generated by Django 5.2.7 on 2025-10-19 00:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Campi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Infracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('LEVE', 'Leve'), ('MEDIA', 'Média'), ('GRAVE', 'Grave'), ('GRAVISSIMA', 'Gravíssima')], max_length=15)),
                ('referencia_artigo', models.CharField(help_text='Art. XX do Regulamento', max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Infração',
                'verbose_name_plural': 'Infrações',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Número de telefone inválido.')])),
                ('endereco', models.TextField(blank=True)),
                ('tipo_vinculo', models.CharField(choices=[('PAI', 'Pai'), ('MAE', 'Mãe'), ('TUTOR', 'Tutor Legal'), ('OUTRO', 'Outro')], max_length=10)),
                ('preferencia_contato', models.CharField(choices=[('EMAIL', 'E-mail'), ('CELULAR', 'Celular'), ('WHATSAPP', 'WhatsApp')], default='EMAIL', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Responsáveis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cursos', to='core.campus')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_sga', models.CharField(max_length=20, unique=True, verbose_name='Matrícula SGA')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('TRANCADO', 'Trancado'), ('EVADIDO', 'Evadido'), ('FORMADO', 'Formado'), ('TRANSFERIDO', 'Transferido')], default='ATIVO', max_length=15)),
                ('data_ingresso', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='estudantes/')),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.campus')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='core.responsavel')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField()),
                ('testemunhas', models.TextField(blank=True, help_text='Nome das testemunhas, separadas por vírgula')),
                ('descricao', models.TextField()),
                ('evidencias', models.FileField(blank=True, null=True, upload_to='evidencias/')),
                ('status', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EM_ANALISE', 'Em Análise Prévia'), ('COMISSAO_DESIGNADA', 'Comissão Designada'), ('ESTUDANTE_NOTIFICADO', 'Estudante Notificado'), ('AGUARDANDO_DEFESA', 'Aguardando Defesa'), ('DEFESA_APRESENTADA', 'Defesa Apresentada'), ('EM_JULGAMENTO', 'Em Julgamento'), ('SANCAO_APLICADA', 'Sanção Aplicada'), ('EM_RECURSO', 'Em Recurso'), ('FINALIZADA', 'Finalizada'), ('ARQUIVADA', 'Arquivada')], default='REGISTRADA', max_length=20)),
                ('prazo_defesa', models.DateField(blank=True, null=True)),
                ('data_defesa', models.DateField(blank=True, null=True)),
                ('defesa_texto', models.TextField(blank=True)),
                ('defesa_arquivo', models.FileField(blank=True, null=True, upload_to='defesas/')),
                ('medida_preventiva', models.TextField(blank=True)),
                ('sancao_detalhes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso')),
                ('estudantes', models.ManyToManyField(related_name='ocorrencias', to='core.estudante')),
                ('infracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.infracao')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data', '-horario'],
            },
        ),
        migrations.CreateModel(
            name='NotificacaoOficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatarios', models.TextField(help_text='E-mails separados por vírgula')),
                ('tipo', models.CharField(choices=[('NOTIFICACAO', 'Notificação'), ('INTIMACAO', 'Intimação'), ('COMUNICADO', 'Comunicado')], max_length=15)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_recebimento', models.DateTimeField(blank=True, null=True)),
                ('meio_envio', models.CharField(choices=[('EMAIL', 'E-mail'), ('CORREIO', 'Correio'), ('PRESENCIAL', 'Presencial'), ('WHATSAPP', 'WhatsApp')], max_length=15)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='comprovantes/')),
                ('texto', models.TextField()),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='core.ocorrencia')),
            ],
            options={
                'verbose_name': 'Notificação Oficial',
                'verbose_name_plural': 'Notificações Oficiais',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_protocolo', models.DateTimeField(auto_now_add=True)),
                ('argumentacao', models.TextField()),
                ('documentos_anexos', models.FileField(blank=True, null=True, upload_to='recursos/')),
                ('parecer_recurso', models.TextField(blank=True)),
                ('data_decisao', models.DateField(blank=True, null=True)),
                ('resultado', models.CharField(choices=[('DEFERIDO', 'Deferido'), ('PARCIALMENTE_DEFERIDO', 'Parcialmente Deferido'), ('INDEFERIDO', 'Indeferido'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=25)),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='core.ocorrencia')),
            ],
            options={
                'ordering': ['-data_protocolo'],
            },
        ),
        migrations.CreateModel(
            name='Sancao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADVERTENCIA_VERBAL', 'Advertência Verbal'), ('ADVERTENCIA_ESCRITA', 'Advertência Escrita'), ('SUSPENSAO', 'Suspensão'), ('TRANSFERENCIA', 'Transferência Compulsória'), ('DESLIGAMENTO', 'Desligamento')], max_length=30)),
                ('descricao', models.TextField()),
                ('infraccoes', models.ManyToManyField(related_name='sancoes_previstas', to='core.infracao')),
            ],
            options={
                'verbose_name': 'Sanção',
                'verbose_name_plural': 'Sanções',
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='sancao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias', to='core.sancao'),
        ),
        migrations.CreateModel(
            name='Servidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siape', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('funcao', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('membro_comissao_disciplinar', models.BooleanField(default=False)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.campus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Servidores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='responsavel_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_registradas', to='core.servidor'),
        ),
        migrations.CreateModel(
            name='DocumentoGerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('REGISTRO', 'Registro de Ocorrência'), ('ATA_ADVERTENCIA', 'Ata de Advertência'), ('TERMO_COMPROMISSO', 'Termo de Compromisso'), ('NOTIFICACAO', 'Notificação/Intimação'), ('PARECER', 'Parecer da Comissão')], max_length=25)),
                ('arquivo', models.FileField(upload_to='documentos_gerados/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('assinado', models.BooleanField(default=False)),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.ocorrencia')),
                ('assinaturas', models.ManyToManyField(blank=True, related_name='documentos_assinados', to='core.servidor')),
            ],
            options={
                'ordering': ['-data_geracao'],
            },
        ),
        migrations.CreateModel(
            name='ComissaoProcessoDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_instauracao', models.DateField(auto_now_add=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('parecer_final', models.TextField(blank=True)),
                ('ocorrencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comissao', to='core.ocorrencia')),
                ('membros', models.ManyToManyField(related_name='comissoes', to='core.servidor')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comissoes_presididas', to='core.servidor')),
            ],
            options={
                'verbose_name': 'Comissão de Processo Disciplinar',
                'verbose_name_plural': 'Comissões de Processos Disciplinares',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, '1º'), (2, '2º')])),
                ('ativa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turmas', to='core.curso')),
            ],
            options={
                'ordering': ['-ano', '-semestre', 'nome'],
                'unique_together': {('nome', 'curso', 'ano', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estudantes', to='core.turma'),
        ),
    ]
