# Generated by Django 5.2.7 on 2025-10-28 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_turma_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='bairro_cidade',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudante',
            name='contato_responsavel',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='estudante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name='estudante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudante',
            name='email_responsavel',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='estudante',
            name='logradouro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='estudante',
            name='turma_periodo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='estudante',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='servidor',
            name='coordenacao',
            field=models.CharField(blank=True, choices=[('CDPD', 'Coordenação Pedagógica'), ('CC', 'Coordenação de Curso'), ('CDRA', 'Coordenação de Registro Acadêmico'), ('NAPNE', 'NAPNE'), ('CDAE', 'Coordenação de Assistência Estudantil'), ('CDAE_PEDAGOGICO', 'CDAE - Pedagógico'), ('CDAE_ASSISTENCIA', 'CDAE - Assistência Estudantil'), ('CDAE_PSICOLOGA', 'CDAE - Psicóloga'), ('CDBA', 'Coordenação de Biblioteca'), ('CGEN', 'Coordenação Geral'), ('CGEN', 'Docente'), ('DREP', 'Direção de Ensino, Pesquisa e Extensão'), ('DG', 'Direção Geral')], max_length=30),
        ),
        migrations.AddField(
            model_name='servidor',
            name='pode_registrar_atendimento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servidor',
            name='pode_visualizar_ficha_aluno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='turma',
            name='periodo',
            field=models.CharField(default=2025, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turma',
            name='sala',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='matricula_sga',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.responsavel'),
        ),
        migrations.AlterField(
            model_name='estudante',
            name='situacao',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('TRANCADO', 'Trancado'), ('EVADIDO', 'Evadido'), ('FORMADO', 'Formado'), ('TRANSFERIDO', 'Transferido')], default='ATIVO', max_length=15),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='turma',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.curso'),
        ),
    ]
