# Generated by Django 5.2.7 on 2025-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_estudante_bairro_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='coordenacao',
            field=models.CharField(blank=True, choices=[('CDPD', 'Coordenação Pedagógica'), ('CC', 'Coordenação de Curso'), ('CDRA', 'Coordenação de Registro Acadêmico'), ('NAPNE', 'NAPNE'), ('CDAE', 'Coordenação de Assistência Estudantil'), ('CDAE_PEDAGOGICO', 'CDAE - Pedagógico'), ('CDAE_ASSISTENCIA', 'CDAE - Assistência Estudantil'), ('CDAE_PSICOLOGA', 'CDAE - Psicóloga'), ('CDBA', 'Coordenação de Biblioteca'), ('CGEN', 'Coordenação Geral'), ('DOCENTE', 'Docente'), ('DREP', 'Direção de Ensino, Pesquisa e Extensão'), ('DG', 'Direção Geral')], max_length=30),
        ),
    ]
