# Generated by Django 5.2.7 on 2025-11-10 19:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servidor_coordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcorrenciaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField()),
                ('tipo_rapido', models.CharField(choices=[('ATRASO', 'Atraso'), ('CELULAR', 'Uso indevido de celular'), ('UNIFORME', 'Sem uniforme'), ('RECUSA', 'Recusa a participar das atividades'), ('AUSENCIA', 'Ausência de sala'), ('SAIDA', 'Saída Antecipada')], max_length=15)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudantes', models.ManyToManyField(related_name='ocorrencias_rapidas', to='core.estudante')),
                ('responsavel_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ocorrencias_rapidas_registradas', to='core.servidor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.turma')),
            ],
            options={
                'verbose_name': 'Ocorrência Rápida',
                'verbose_name_plural': 'Ocorrências Rápidas',
                'ordering': ['-data', '-horario'],
            },
        ),
    ]
