# Generated by Django 5.2.7 on 2025-11-11 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ocorrenciarapida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrenciarapida',
            name='tipo_rapido',
            field=models.CharField(choices=[('ATRASO', 'Atraso'), ('CELULAR', 'Uso indevido de celular'), ('UNIFORME', 'Sem uniforme'), ('RECUSA', 'Recusa a participar das atividades'), ('AUSENCIA', 'Ausência de sala'), ('SAIDA', 'Saída Antecipada'), ('BIBLIO', 'Acesso a Biblioteca sem autorização')], max_length=15),
        ),
    ]
