# Generated by Django 5.2.7 on 2025-11-12 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_ocorrenciarapida_tipo_rapido'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudante',
            name='foto_url',
            field=models.URLField(blank=True, help_text='Link direto da imagem no Google Drive. Use o formato: https://drive.google.com/uc?export=view&id=ID_DA_IMAGEM', null=True),
        ),
    ]
