# Generated by Django 5.2.7 on 2025-11-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estudante_foto_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='contato_responsavel',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='email_responsavel',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='estudante',
            name='cep',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='estudante',
            name='responsaveis',
            field=models.ManyToManyField(blank=True, related_name='estudantes', to='core.responsavel'),
        ),
    ]
