# Generated by Django 5.2.7 on 2025-11-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_adicionar_campos_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsavel',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
