# Generated by Django 5.2.7 on 2025-11-15 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_responsavel_ultima_atualizacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentogerado',
            name='ocorrencia_rapida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.ocorrenciarapida'),
        ),
        migrations.AlterField(
            model_name='documentogerado',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='core.ocorrencia'),
        ),
        migrations.AlterField(
            model_name='documentogerado',
            name='tipo_documento',
            field=models.CharField(choices=[('REGISTRO', 'Registro de Ocorrência'), ('ATA_ADVERTENCIA', 'Ata de Advertência'), ('TERMO_COMPROMISSO', 'Termo de Compromisso'), ('NOTIFICACAO', 'Notificação/Intimação'), ('PARECER', 'Parecer da Comissão'), ('RECIBO_TERMICO', 'Recibo Térmico')], max_length=25),
        ),
    ]
