# Generated by Django 5.2.7 on 2025-11-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_documentogerado_ocorrencia_rapida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrenciaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField()),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Ocorrência Rápida',
                'verbose_name_plural': 'Tipos de Ocorrência Rápida',
            },
        ),
        migrations.RemoveField(
            model_name='ocorrenciarapida',
            name='tipo_rapido',
        ),
        migrations.AddField(
            model_name='ocorrenciarapida',
            name='tipos_rapidos',
            field=models.ManyToManyField(related_name='ocorrencias_rapidas', to='core.tipoocorrenciarapida', verbose_name='Tipos de Ocorrência Rápida'),
        ),
    ]
