# Generated by Django 5.2.7 on 2025-12-01 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_tipoocorrenciarapida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoLimiteOcorrenciaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_mensal', models.IntegerField(default=3, help_text='Número de ocorrências do mesmo tipo no mês que gera alerta')),
                ('gerar_notificacao_sistema', models.BooleanField(default=True, help_text='Gerar notificação no sistema quando limite for atingido')),
                ('gerar_email_coordenacao', models.BooleanField(default=True, help_text='Enviar e-mail para coordenação quando limite for atingido')),
                ('gerar_email_responsaveis', models.BooleanField(default=False, help_text='Enviar e-mail para responsáveis do estudante')),
                ('coordenacoes_notificar', models.CharField(choices=[('CDPD', 'Coordenação Pedagógica'), ('CC', 'Coordenação de Curso'), ('CDRA', 'Coordenação de Registro Acadêmico'), ('NAPNE', 'NAPNE'), ('CDAE', 'Coordenação de Assistência Estudantil'), ('CDAE_PEDAGOGICO', 'CDAE - Pedagógico'), ('CDAE_ASSISTENCIA', 'CDAE - Assistência Estudantil'), ('CDAE_PSICOLOGA', 'CDAE - Psicóloga'), ('CDBA', 'Coordenação de Biblioteca'), ('CGEN', 'Coordenação Geral'), ('DOCENTE', 'Docente'), ('DREP', 'Direção de Ensino, Pesquisa e Extensão'), ('DG', 'Direção Geral')], default='CDPD', help_text='Coordenação a ser notificada (ex: CDPD, CC, NAPNE)', max_length=500)),
                ('ativo', models.BooleanField(default=True, help_text='Se esta configuração está ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tipo_ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes_limite', to='core.tipoocorrenciarapida', verbose_name='Tipo de Ocorrência')),
            ],
            options={
                'verbose_name': 'Configuração de Limite',
                'verbose_name_plural': 'Configurações de Limites',
                'unique_together': {('tipo_ocorrencia',)},
            },
        ),
        migrations.CreateModel(
            name='AlertaLimiteOcorrenciaRapida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.DateField(help_text='Primeiro dia do mês de referência')),
                ('quantidade_ocorrencias', models.IntegerField(help_text='Número de ocorrências que gerou o alerta')),
                ('notificacao_sistema_criada', models.BooleanField(default=False)),
                ('email_coordenacao_enviado', models.BooleanField(default=False)),
                ('email_responsaveis_enviado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_limite', to='core.estudante')),
                ('tipo_ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_gerados', to='core.tipoocorrenciarapida')),
                ('configuracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.configuracaolimiteocorrenciarapida')),
            ],
            options={
                'verbose_name': 'Alerta de Limite',
                'verbose_name_plural': 'Alertas de Limites',
                'ordering': ['-criado_em'],
                'unique_together': {('estudante', 'tipo_ocorrencia', 'mes_referencia')},
            },
        ),
    ]
