# Generated by Django 5.2.7 on 2026-02-05 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_configuracaolimiteocorrenciarapida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParecerMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('SEMIFINAL', 'Parecer Semifinal'), ('FINAL', 'Parecer Final')], max_length=10)),
                ('decisao', models.CharField(choices=[('ARQUIVAR', 'Arquivar'), ('ADVERTENCIA_VERBAL', 'Advertência Verbal'), ('ADVERTENCIA_ESCRITA', 'Advertência Escrita'), ('SUSPENSAO', 'Suspensão'), ('OUTRAS_MEDIDAS', 'Outras Medidas')], max_length=30)),
                ('justificativa', models.TextField()),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('mudou_voto', models.BooleanField(default=False)),
                ('justificativa_mudanca', models.TextField(blank=True)),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres_dados', to='core.servidor')),
                ('ocorrencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pareceres', to='core.ocorrencia')),
            ],
            options={
                'ordering': ['-data_registro'],
                'unique_together': {('ocorrencia', 'membro', 'tipo')},
            },
        ),
    ]
