# Generated by Django 5.2.7 on 2025-10-20 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='usuarios_interessados',
            field=models.ManyToManyField(blank=True, related_name='ocorrencias_interesse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOVA_OCORRENCIA', 'Nova Ocorrência'), ('ATUALIZACAO_STATUS', 'Atualização de Status'), ('COMENTARIO', 'Novo Comentário'), ('PRAZO', 'Lembrete de Prazo'), ('DEFESA', 'Defesa Apresentada'), ('SANCAO', 'Sanção Aplicada')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ocorrencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ocorrencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PreferenciaNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receber_email_novas_ocorrencias', models.BooleanField(default=True)),
                ('receber_email_atualizacoes', models.BooleanField(default=True)),
                ('receber_email_prazos', models.BooleanField(default=True)),
                ('receber_notificacoes_urgentes', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_notificacao', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
