# Generated by Django 5.2.7 on 2025-10-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ocorrencia_ultima_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='semestre',
            field=models.IntegerField(choices=[(0, 'Anual'), (1, '1º'), (2, '2º')]),
        ),
    ]
