# Generated by Django 5.2.7 on 2025-10-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_estudante_bairro_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SituacaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#6b7280', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenacao', models.CharField(choices=[('CDPD', 'Coordenação Pedagógica'), ('CC', 'Coordenação de Curso'), ('CDRA', 'Coordenação de Registro Acadêmico'), ('NAPNE', 'NAPNE'), ('CDAE', 'Coordenação de Assistência Estudantil'), ('CDAE_PEDAGOGICO', 'CDAE - Pedagógico'), ('CDAE_ASSISTENCIA', 'CDAE - Assistência Estudantil'), ('CDAE_PSICOLOGA', 'CDAE - Psicóloga'), ('CDBA', 'Coordenação de Biblioteca'), ('CGEN', 'Coordenação Geral'), ('CGEN', 'Docente'), ('DREP', 'Direção de Ensino'), ('DG', 'Direção Geral')], max_length=30)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('origem', models.CharField(choices=[('ESPONTANEO', 'Espontâneo'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('SOLICITACAO_DOCENTE', 'Solicitação de Docente'), ('SOLICITACAO_COORDENACAO', 'Solicitação de Coordenação'), ('OUTRO', 'Outro')], max_length=30)),
                ('informacoes', models.TextField()),
                ('observacoes', models.TextField(blank=True)),
                ('anexos', models.FileField(blank=True, null=True, upload_to='atendimentos/')),
                ('publicar_ficha_aluno', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudantes', models.ManyToManyField(related_name='atendimentos', to='core.estudante')),
                ('servidor_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos_realizados', to='core.servidor')),
                ('servidores_participantes', models.ManyToManyField(blank=True, related_name='atendimentos_participacao', to='core.servidor')),
                ('situacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimentos.situacaoatendimento')),
                ('tipo_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='atendimentos.tipoatendimento')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'ordering': ['-data', '-hora'],
            },
        ),
    ]
