# Generated by Django 5.2.7 on 2025-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacaoatendimento',
            options={'verbose_name': 'Situação de Atendimento', 'verbose_name_plural': 'Situações de Atendimento'},
        ),
        migrations.AlterModelOptions(
            name='tipoatendimento',
            options={'verbose_name': 'Tipo de Atendimento', 'verbose_name_plural': 'Tipos de Atendimento'},
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='coordenacao',
            field=models.CharField(choices=[('CDPD', 'Coordenação Pedagógica'), ('CC', 'Coordenação de Curso'), ('CDRA', 'Coordenação de Registro Acadêmico'), ('NAPNE', 'NAPNE'), ('CDAE', 'Coordenação de Assistência Estudantil'), ('CDAE_PEDAGOGICO', 'CDAE - Pedagógico'), ('CDAE_ASSISTENCIA', 'CDAE - Assistência Estudantil'), ('CDAE_PSICOLOGA', 'CDAE - Psicóloga'), ('CDBA', 'Coordenação de Biblioteca'), ('CGEN', 'Coordenação Geral'), ('DOCENTE', 'Docente'), ('DREP', 'Direção de Ensino, Pesquisa e Extensão'), ('DG', 'Direção Geral')], max_length=30),
        ),
    ]
