# Generated by Django 5.2.7 on 2025-11-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_alter_situacaoatendimento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='origem',
            field=models.CharField(choices=[('PRESENCIAL', 'Presencial'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('SOLICITACAO_DOCENTE', 'Solicitação de Docente'), ('SOLICITACAO_COORDENACAO', 'Solicitação de Coordenação'), ('CONTATO_TELEFONICO', 'Contato Telefônico'), ('CONTATO_WHATSAPP', 'Contato Whatsapp'), ('RESPONSAVEL', 'Responsável'), ('OUTRO', 'Outro')], max_length=30),
        ),
    ]
