# Generated by Django 5.2.7 on 2025-11-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_estudante_bairro_cidade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NecessidadeEspecifica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Necessidade Específica",
                "verbose_name_plural": "Necessidades Específicas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="SetorEncaminhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=20)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Setor de Encaminhamento",
                "verbose_name_plural": "Setores de Encaminhamento",
            },
        ),
        migrations.CreateModel(
            name="StatusAtendimentoNAPNE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cor", models.CharField(default="#6b7280", max_length=7)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Status de Atendimento NAPNE",
                "verbose_name_plural": "Status de Atendimentos NAPNE",
            },
        ),
        migrations.CreateModel(
            name="TipoAtendimentoNAPNE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Tipo de Atendimento NAPNE",
                "verbose_name_plural": "Tipos de Atendimento NAPNE",
            },
        ),
        migrations.CreateModel(
            name="FichaEstudanteNAPNE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("necessidade_especifica", models.TextField()),
                ("telefone", models.CharField(max_length=20)),
                ("laudo_apresentado", models.BooleanField(default=False)),
                (
                    "emails_enviados",
                    models.TextField(blank=True, help_text="Log de emails enviados"),
                ),
                (
                    "observacoes_laudos_historico",
                    models.TextField(
                        blank=True, help_text="Histórico de observações dos laudos"
                    ),
                ),
                (
                    "observacao_laudo_atual",
                    models.TextField(blank=True, help_text="Observação atual do laudo"),
                ),
                ("desempenho_1bim", models.TextField(blank=True)),
                ("desempenho_2bim", models.TextField(blank=True)),
                ("desempenho_3bim", models.TextField(blank=True)),
                ("desempenho_4bim", models.TextField(blank=True)),
                ("resultado_final", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atendido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="estudantes_napne",
                        to="core.servidor",
                    ),
                ),
                (
                    "estudante",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha_napne",
                        to="core.estudante",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.turma"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ficha NAPNE",
                "verbose_name_plural": "Fichas NAPNE",
                "ordering": ["estudante__nome"],
            },
        ),
        migrations.CreateModel(
            name="AtendimentoNAPNE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("ESPONTANEO", "Espontâneo"),
                            ("ENCAMINHAMENTO", "Encaminhamento"),
                            ("SOLICITACAO_DOCENTE", "Solicitação de Docente"),
                            ("SOLICITACAO_COORDENACAO", "Solicitação de Coordenação"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("data", models.DateField()),
                (
                    "detalhamento",
                    models.TextField(verbose_name="Detalhamento do Atendimento"),
                ),
                ("acoes", models.TextField(verbose_name="Ações Realizadas")),
                ("resumo_atendimento", models.TextField(blank=True)),
                (
                    "publicar_ficha_aluno",
                    models.BooleanField(
                        default=False, verbose_name="Publicar na Ficha do Aluno"
                    ),
                ),
                ("data_ultima_atualizacao_status", models.DateTimeField(auto_now=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "atendido_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos_napne_realizados",
                        to="core.servidor",
                    ),
                ),
                (
                    "estudante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="atendimentos_napne",
                        to="core.estudante",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.turma"
                    ),
                ),
                (
                    "laudo_previo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atendimentos",
                        to="napne.fichaestudantenapne",
                    ),
                ),
                (
                    "necessidades_especificas",
                    models.ManyToManyField(
                        blank=True, to="napne.necessidadeespecifica"
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="napne.statusatendimentonapne",
                    ),
                ),
                (
                    "tipo_atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="napne.tipoatendimentonapne",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atendimento NAPNE",
                "verbose_name_plural": "Atendimentos NAPNE",
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="ObservacaoEncaminhamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacao", models.TextField()),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "atendimento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes_encaminhamento",
                        to="napne.atendimentonapne",
                    ),
                ),
                (
                    "setor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="napne.setorencaminhamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Observação de Encaminhamento",
                "verbose_name_plural": "Observações de Encaminhamento",
                "ordering": ["-criado_em"],
            },
        ),
    ]
