# Generated by Django 5.2.7 on 2025-10-28 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_estudante_bairro_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConselhoClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('data_realizacao', models.DateField()),
                ('informacoes_gerais', models.TextField(blank=True)),
                ('pontos_positivos', models.TextField(blank=True)),
                ('pontos_atencao', models.TextField(blank=True)),
                ('encaminhamentos', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coordenacao_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conselhos_coordenados', to='core.servidor')),
                ('coordenacao_pedagogica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conselhos_pedagogicos', to='core.servidor')),
                ('docentes_participantes', models.ManyToManyField(related_name='conselhos_participacao', to='core.servidor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conselhos', to='core.turma')),
            ],
            options={
                'verbose_name': 'Conselho de Classe',
                'verbose_name_plural': 'Conselhos de Classe',
                'ordering': ['-data_realizacao'],
                'unique_together': {('turma', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('carga_horaria', models.IntegerField()),
                ('ementa', models.TextField(blank=True)),
                ('ativa', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas', to='core.curso')),
            ],
        ),
        migrations.CreateModel(
            name='FichaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('estudante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='core.estudante')),
            ],
            options={
                'verbose_name': 'Ficha do Aluno',
                'verbose_name_plural': 'Fichas dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='InformacaoEstudanteConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes_gerais', models.TextField(blank=True)),
                ('frequencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('situacao_geral', models.CharField(blank=True, max_length=50)),
                ('participacao', models.TextField(blank=True)),
                ('relacionamento', models.TextField(blank=True)),
                ('dificuldades', models.TextField(blank=True)),
                ('potencialidades', models.TextField(blank=True)),
                ('necessita_acompanhamento', models.BooleanField(default=False)),
                ('encaminhamento_cdpd', models.BooleanField(default=False)),
                ('encaminhamento_cdae', models.BooleanField(default=False)),
                ('encaminhamento_napne', models.BooleanField(default=False)),
                ('observacoes_encaminhamento', models.TextField(blank=True)),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informacoes_estudantes', to='pedagogico.conselhoclasse')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='InformacaoDisciplinaConselho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('frequencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
                ('informacao_estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='pedagogico.informacaoestudanteconselho')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplinaTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_lecionadas', to='core.servidor')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_turma', to='core.turma')),
            ],
            options={
                'unique_together': {('disciplina', 'turma', 'periodo')},
            },
        ),
    ]
