# Generated by Django 5.2.7 on 2025-11-08 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servidor_coordenacao'),
        ('pedagogico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome'], 'verbose_name': 'Disciplina', 'verbose_name_plural': 'Disciplinas'},
        ),
        migrations.AlterModelOptions(
            name='disciplinaturma',
            options={'verbose_name': 'Disciplina da Turma', 'verbose_name_plural': 'Disciplinas das Turmas'},
        ),
        migrations.AlterModelOptions(
            name='informacaodisciplinaconselho',
            options={'verbose_name': 'Informação de Disciplina no Conselho', 'verbose_name_plural': 'Informações de Disciplinas no Conselho'},
        ),
        migrations.AlterModelOptions(
            name='informacaoestudanteconselho',
            options={'verbose_name': 'Informação do Estudante no Conselho', 'verbose_name_plural': 'Informações dos Estudantes no Conselho'},
        ),
        migrations.AlterField(
            model_name='informacaoestudanteconselho',
            name='encaminhamento_cdae',
            field=models.BooleanField(default=False, verbose_name='Encaminhamento CDAE'),
        ),
        migrations.AlterField(
            model_name='informacaoestudanteconselho',
            name='encaminhamento_cdpd',
            field=models.BooleanField(default=False, verbose_name='Encaminhamento CDPD'),
        ),
        migrations.AlterField(
            model_name='informacaoestudanteconselho',
            name='encaminhamento_napne',
            field=models.BooleanField(default=False, verbose_name='Encaminhamento NAPNE'),
        ),
        migrations.AlterUniqueTogether(
            name='informacaoestudanteconselho',
            unique_together={('conselho', 'estudante')},
        ),
    ]
