# Generated by Django 5.2.7 on 2025-11-10 11:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servidor_coordenacao'),
        ('pedagogico', '0002_alter_disciplina_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conselhoclasse',
            name='aberto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conselhoclasse',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conselhos_criados', to='core.servidor'),
        ),
        migrations.AddField(
            model_name='conselhoclasse',
            name='data_abertura',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='conselhoclasse',
            name='data_fechamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conselhoclasse',
            name='perfil_turma',
            field=models.TextField(blank=True, verbose_name='Perfil da turma segundo os professores'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='bimestres_ativos',
            field=models.CharField(default='1,2,3,4', help_text='Bimestres em que a disciplina é ofertada (ex: 1,2)', max_length=20),
        ),
        migrations.AddField(
            model_name='informacaoestudanteconselho',
            name='observacoes_napne',
            field=models.TextField(blank=True, verbose_name='Observações docentes das adaptações realizadas (NAPNE)'),
        ),
        migrations.AlterField(
            model_name='conselhoclasse',
            name='coordenacao_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conselhos_coordenados', to='core.servidor'),
        ),
        migrations.AlterField(
            model_name='conselhoclasse',
            name='docentes_participantes',
            field=models.ManyToManyField(blank=True, related_name='conselhos_participacao', to='core.servidor'),
        ),
        migrations.AlterField(
            model_name='disciplinaturma',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disciplinas_lecionadas', to='core.servidor'),
        ),
        migrations.AlterField(
            model_name='informacaoestudanteconselho',
            name='observacoes_gerais',
            field=models.TextField(blank=True, verbose_name='Observações sobre o estudante'),
        ),
        migrations.CreateModel(
            name='ObservacaoDocenteEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Observações sobre o estudante')),
                ('observacao_napne', models.TextField(blank=True, verbose_name='Observações das adaptações realizadas (NAPNE)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('preenchido', models.BooleanField(default=False)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
                ('informacao_estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_docentes', to='pedagogico.informacaoestudanteconselho')),
            ],
            options={
                'verbose_name': 'Observação Docente do Estudante',
                'verbose_name_plural': 'Observações Docentes dos Estudantes',
                'ordering': ['disciplina__nome'],
                'unique_together': {('informacao_estudante', 'docente', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='ObservacaoDocenteTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(verbose_name='Perfil da turma segundo o professor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conselho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observacoes_turma', to='pedagogico.conselhoclasse')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedagogico.disciplina')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servidor')),
            ],
            options={
                'verbose_name': 'Observação Docente da Turma',
                'verbose_name_plural': 'Observações Docentes da Turma',
                'unique_together': {('conselho', 'docente', 'disciplina')},
            },
        ),
        migrations.DeleteModel(
            name='InformacaoDisciplinaConselho',
        ),
    ]
