# Generated by Django 5.2.7 on 2026-02-05 18:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0015_parecermembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigRefeitorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('CAFE', 'Café da Manhã'), ('ALMOCO', 'Almoço'), ('LANCHE', 'Lanche da Tarde'), ('JANTAR', 'Jantar')], max_length=50, unique=True)),
                ('horario_inicio', models.TimeField()),
                ('horario_fim', models.TimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('intervalo_minimo_horas', models.IntegerField(default=3, help_text='Intervalo mínimo em horas entre refeições do mesmo tipo')),
            ],
            options={
                'verbose_name': 'Configuração de Refeitório',
                'verbose_name_plural': 'Configurações de Refeitório',
                'ordering': ['horario_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BloqueioAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_fim', models.DateField(blank=True, help_text='Deixe em branco para bloqueio permanente', null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bloqueios_criados', to='core.servidor')),
                ('estudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_refeitorio', to='core.estudante')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_refeitorio', to='core.servidor')),
            ],
            options={
                'verbose_name': 'Bloqueio de Acesso',
                'verbose_name_plural': 'Bloqueios de Acesso',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRefeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_refeicao', models.CharField(max_length=20)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('codigo_barras_usado', models.CharField(blank=True, max_length=50)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('estudante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='core.estudante')),
                ('servidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='core.servidor')),
            ],
            options={
                'verbose_name': 'Registro de Refeição',
                'verbose_name_plural': 'Registros de Refeições',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['data_hora', 'estudante'], name='refeitorio__data_ho_fe69d7_idx'), models.Index(fields=['data_hora', 'servidor'], name='refeitorio__data_ho_5762a2_idx')],
            },
        ),
    ]
