# Generated by Django 5.2.7 on 2025-11-09 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_alter_servidor_coordenacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipacaoEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolsista', models.BooleanField(default=False)),
                ('valor_bolsa', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudante')),
            ],
            options={
                'verbose_name': 'Participação de Estudante',
                'verbose_name_plural': 'Participações de Estudantes',
                'ordering': ['estudante__nome'],
            },
        ),
        migrations.CreateModel(
            name='ParticipacaoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(help_text='Formato: YYYY.S (ex: 2024.1)', max_length=10)),
                ('horas_semanais', models.DecimalField(decimal_places=1, help_text='Horas semanais dedicadas ao projeto', max_digits=4, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(12)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servidor')),
            ],
            options={
                'verbose_name': 'Participação de Servidor',
                'verbose_name_plural': 'Participações de Servidores',
                'ordering': ['-semestre', 'servidor__nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=50, unique=True, verbose_name='Nº do Processo')),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('PESQUISA', 'Pesquisa'), ('EXTENSAO', 'Extensão')], default='EXTENSAO', max_length=10)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('tema', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('envolve_estudantes', models.BooleanField(default=False, verbose_name='Envolve alunos pesquisadores/extensionistas?')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('FINALIZADO', 'Finalizado'), ('PENDENTE', 'Pendente')], default='ATIVO', max_length=15)),
                ('observacoes', models.TextField(blank=True)),
                ('periodicidade_relatorio', models.IntegerField(default=6, help_text='Periodicidade em meses', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Periodicidade do Relatório (meses)')),
                ('data_ultimo_relatorio', models.DateField(blank=True, null=True)),
                ('proximo_relatorio', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_coordenados', to='core.servidor', verbose_name='Coordenador')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos_criados', to='core.servidor')),
                ('estudantes', models.ManyToManyField(blank=True, related_name='projetos', through='projetos.ParticipacaoEstudante', to='core.estudante')),
                ('servidores_participantes', models.ManyToManyField(blank=True, related_name='projetos_participantes', through='projetos.ParticipacaoServidor', to='core.servidor')),
            ],
            options={
                'verbose_name': 'Projeto de Extensão/Pesquisa',
                'verbose_name_plural': 'Projetos de Extensão/Pesquisa',
                'ordering': ['-data_inicio', 'titulo'],
                'permissions': [('coordenar_projetos', 'Pode coordenar projetos (Coord. Pesquisa/Extensão)')],
            },
        ),
        migrations.AddField(
            model_name='participacaoservidor',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
        ),
        migrations.AddField(
            model_name='participacaoestudante',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetos.projeto'),
        ),
        migrations.CreateModel(
            name='AlertaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROXIMO', 'Próximo do prazo'), ('VENCIDO', 'Prazo vencido')], max_length=10)),
                ('data_alerta', models.DateField()),
                ('visualizado', models.BooleanField(default=False)),
                ('data_visualizacao', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='projetos.projeto')),
            ],
            options={
                'verbose_name': 'Alerta de Relatório',
                'verbose_name_plural': 'Alertas de Relatórios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='participacaoservidor',
            unique_together={('projeto', 'servidor', 'semestre')},
        ),
        migrations.AlterUniqueTogether(
            name='participacaoestudante',
            unique_together={('projeto', 'estudante')},
        ),
    ]
