# Generated by Django 5.2.7 on 2025-11-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='tipo',
            field=models.CharField(choices=[('PESQUISA', 'Pesquisa'), ('EXTENSAO', 'Extensão'), ('GRI', 'Gestão e Representação Institucional')], default='EXTENSAO', max_length=10),
        ),
    ]
